#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        systemctl stop raspisump.service > /dev/null 2>&1 || true
        systemctl disable raspisump.service > /dev/null 2>&1 || true
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

#DEBHELPER#
exit 0
