#!/bin/bash
set -e

case "$1" in
    purge)
        systemctl daemon-reload || true
        rm -rf /etc/raspi-sump
        if getent passwd raspisump > /dev/null 2>&1; then
            deluser --system raspisump || true
        fi
        ;;

    remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
        systemctl daemon-reload || true
        ;;

    *)
        echo "postrm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac

# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'rsumpwebchart.service' 'rsumpwebchart.timer' >/dev/null || true
	fi
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = remove ] && [ -d /run/systemd/system ] ; then
	systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.24.2
if [ "$1" = "purge" ]; then
	if [ -x "/usr/bin/deb-systemd-helper" ]; then
		deb-systemd-helper purge 'raspisump.service' >/dev/null || true
	fi
fi
# End automatically added section

exit 0
