#!/bin/bash
set -e

case "$1" in
    remove|upgrade|deconfigure)
        systemctl stop raspisump.service || true
        systemctl stop rsumpwebchart.timer || true
        systemctl disable raspisump.service || true
        systemctl disable rsumpwebchart.timer || true
        ;;

    failed-upgrade)
        ;;

    *)
        echo "prerm called with unknown argument '$1'" >&2
        exit 1
        ;;
esac


# Automatically added by dh_python3
if command -v py3clean >/dev/null 2>&1; then
	py3clean -p raspisump 
else
	dpkg -L raspisump | sed -En -e '/^(.*)\/(.+)\.py$/s,,rm "\1/__pycache__/\2".*,e'
	find /usr/lib/python3/dist-packages/ -type d -name __pycache__ -empty -print0 | xargs --null --no-run-if-empty rmdir
fi

# End automatically added section

exit 0
